name: Deployment

on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        description: Type of Release
        options:
          - major
          - minor
          - patch

concurrency: production
jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code to update tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'

      - name: Update Dry Run tag version
        id: tagger-dry
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DRY_RUN: true

      - name: Update tag version
        id: tagger
        uses: anothrNick/github-tag-action@v1
        env:
          DEFAULT_BUMP: ${{ github.event.inputs.release-type }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false

  build:
    runs-on: ubuntu-latest
    needs: tag
    if: ${{ needs.tag.result == 'success' }}
    steps:
      - name: Get current tag
        id: current-tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Checkout code
        if: ${{ needs.tag.outputs.tagger.outputs.tag == steps.current-tag.outputs.tag }}
        uses: actions/checkout@v2

      - name: Set up QEMU
        if: ${{ needs.tag.outputs.tagger.outputs.tag == steps.current-tag.outputs.tag }}
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        if: ${{ needs.tag.outputs.tagger.outputs.tag == steps.current-tag.outputs.tag }}
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: ${{ needs.tag.outputs.tagger.outputs.tag == steps.current-tag.outputs.tag }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Add Environment variables
        if: ${{ needs.tag.outputs.tagger.outputs.tag == steps.current-tag.outputs.tag }}
        run: |
          echo "SERVER_ONLY_DATABASE_URL=${{ secrets.SERVER_ONLY_DATABASE_URL }}" >> .env
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env

      - name: Build and push to DockerHub
        if: ${{ needs.tag.outputs.tagger.outputs.tag == steps.current-tag.outputs.tag }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: "dborovskiy00/nextjs:${{ needs.tag.outputs.tagger.outputs.tag }}"

  trigger-argocd-workflow:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.result == 'success' }}
    steps:
      - name: Trigger Workflow in ArgoCD Repository
        run: |
          repo_owner="${{ secrets.OWNER }}"
          event_type="trigger-workflow"
          version="${{ needs.tag.outputs.tagger.outputs.tag }}"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/dborovskiy00/${{ secrets.HELM_REPO_NAME }}/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"version\": \"$version\", \"unit\": false, \"integration\": true}}"
