name: Deployment

on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        description: Type of Release
        options:
          - major
          - minor
          - patch

concurrency: production
jobs:
  deploy-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code to update tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'

      - name: Update Dry Run tag version
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DRY_RUN: true

      - name: Update tag version
        id: tagger
        uses: anothrNick/github-tag-action@v1
        env:
          DEFAULT_BUMP: ${{ github.event.inputs.release-type }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false

      - name: Show tags
        run: |
          echo "old: ${{ steps.tagger.outputs.tag }}" \
          echo "new: ${{ steps.tagger.outputs.new_tag }}"

      - name: Checkout code
        if: ${{ steps.tagger.outputs.tag != steps.tagger.outputs.new_tag }}
        uses: actions/checkout@v2

      - name: Set up QEMU
        if: ${{ steps.tagger.outputs.tag != steps.tagger.outputs.new_tag }}
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        if: ${{ steps.tagger.outputs.tag != steps.tagger.outputs.new_tag }}
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: ${{ steps.tagger.outputs.tag != steps.tagger.outputs.new_tag }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push to DockerHub
        if: ${{ steps.tagger.outputs.tag != steps.tagger.outputs.new_tag }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: "dborovskiy00/nextjs:${{ steps.tagger.outputs.tag }}"

      - name: Trigger Workflow in ArgoCD Repository
        if: ${{ steps.tagger.outputs.tag != steps.tagger.outputs.new_tag }}
        run: |
          repo_owner="${{ secrets.OWNER }}"
          repo_name="${{ secrets.ARGO_REPO_NAME }}"
          event_type="trigger-workflow"
          version="${{ steps.tagger.outputs.tag }}"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/dborovskiy00/argocd-k8s/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"version\": \"$version\", \"unit\": false, \"integration\": true}}"
